---
- name: Deploy K8s infra
  hosts: k8s_cp
  become: true  # This applies to all tasks in this play
  serial: 1
  vars:
    kubernetes_version: "1.34"
    cni: "flannel"
    ansible_user: vagrant
    containerd_config_cgroup_driver_systemd: true
  tasks:

    - name: Install package dependencies for Ansible k8s support
      package:
        name: python3-pip
        state: present

    - name: Install pip modules for Ansible k8s support
      pip:
        name:
          - pyyaml
          - kubernetes

    - name: Download Helm tarball
      get_url:
        url: "https://get.helm.sh/helm-v3.19.0-linux-amd64.tar.gz"
        dest: /tmp/helm-v3.19.0-linux-amd64.tar.gz
        mode: 0644

    - name: Extract Helm binary
      unarchive:
        src: /tmp/helm-v3.19.0-linux-amd64.tar.gz
        dest: /tmp
        remote_src: true

    - name: Copy Helm binary to /usr/loca/sbin
      copy:
        src: /tmp/linux-amd64/helm
        dest: /usr/local/sbin/helm
        mode: 0755
        remote_src: true

    - name: Download kubecolor package
      get_url:
        url: "https://github.com/kubecolor/kubecolor/releases/download/v0.5.1/kubecolor_0.5.1_linux_amd64.rpm"
        dest: /tmp/kubecolor_0.5.1_linux_amd64.rpm
        mode: 0644

    - name: Install kubecolor package
      dnf:
        name: /tmp/kubecolor_0.5.1_linux_amd64.rpm
        state: present
        disable_gpg_check: true

    - name: Kubeconfig path for Vagrant user
      file:
        path: /home/vagrant/.kube
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0700'
      become: true

    - name: Kubeconfig file for Vagrant user
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: true
        owner: vagrant
        group: vagrant
        mode: '0600'
      become: true

    - name: Set kubecolor alias in Vagrant user .bash_profile
      lineinfile:
        path: /home/vagrant/.bash_profile
        line: 'alias k="kubecolor"'
        insertafter: EOF
        #create: yes
        state: present
        owner: vagrant
      become: true

    - name: Create k8s infra namespace
      kubernetes.core.k8s:
        name: infra
        api_version: v1
        kind: Namespace
        state: present

    - name: Add Prometheus chart repo
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: https://prometheus-community.github.io/helm-charts
        force_update: true
        state: present

    - name: Deploy kube-prometheus-stack Helm chart
      kubernetes.core.helm:
        name: po
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: infra
        values:
          grafana:
            enabled: true
          prometheus:
            prometheusSpec:
              retention: 30d
          alertmanager:
            enabled: false
        state: present

    - name: Add openEBS chart repo
      kubernetes.core.helm_repository:
        name: openebs
        repo_url: https://openebs.github.io/openebs
        force_update: true
        state: present

    - name: Deploy openEBS Helm chart
      kubernetes.core.helm:
        name: openebs
        chart_ref: openebs/openebs
        release_namespace: infra
        values:
          engines:
            local:
              zfs:
                enabled: true
            replicated:
              mayastor:
                enabled: false
          loki:
            enabled: false
          minio:
            enabled: false
          alloy:
            enabled: false
        state: present

    - name: Apply openEBS ZFS Storage Class
      kubernetes.core.k8s:
        state: present # Ensures the resource exists and matches the definition
        definition: "{{ lookup('file', 'files/openebs-zfs-sc.yml') | from_yaml }}"
