---
- name: Apply k8s control plane
  hosts: k8s_cp
  become: true # This applies to all tasks in this play
  serial: 1
  vars:
    kubernetes_version: "1.32"
    cni: "flannel"
    kubernetes_flannel_manifest_file: "/home/vagrant/kube-flannel.yml"
    ansible_user: vagrant
    containerd_config_cgroup_driver_systemd: true

  pre_tasks:
    - name: Disable swap immediately
      command: swapoff -a
      when: ansible_swaptotal_mb | int > 0
    - name: Remove any swap entries from /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '^\s*(.+\s+)swap(\s+.+)$'
        replace: '# \1swap\2'
      become: true

#    # firewalld whitelisting for all k8s nodes
#    - name: Permit traffic in default zone for kube-control-plane service
#      ansible.posix.firewalld:
#        service: kube-control-plane
#        permanent: true
#        state: enabled
#
#    - name: Permit traffic in default zone for kube-control-plane-secure service
#      ansible.posix.firewalld:
#        service: kube-control-plane-secure
#        permanent: true
#        state: enabled
#
#    - name: Permit traffic in default zone for kubelet service
#      ansible.posix.firewalld:
#        service: kubelet
#        permanent: true
#        state: enabled
#
#    - name: Permit traffic in default zone on port 8285/ucp for Flannel VXLAN
#      ansible.posix.firewalld:
#        port: 8285/udp
#        permanent: true
#        zone: public
#        state: enabled
#
#    - name: Permit traffic in default zone on port 8472/ucp for Flannel VXLAN
#      ansible.posix.firewalld:
#        port: 8472/udp
#        permanent: true
#        zone: public
#        state: enabled
#
#    - name: Enable masquerade in public zone
#      ansible.posix.firewalld:
#        masquerade: true
#        zone: public
#        permanent: true
#        state: enabled
#
#    - name: Allow traffic from 10.244.0.0/16 (Flannel) in public zone
#      ansible.posix.firewalld:
#        source: 10.244.0.0/16
#        zone: public
#        state: enabled
#
#    # reload firewalld to apply changes
#    - name: Always reload firewalld
#      service:
#        name: firewalld
#        state: reloaded


    - name: Copy kube-flannel.yml to /home/vagrant/
      ansible.builtin.copy:
        src: files/kube-flannel.yml
        dest: /home/vagrant/kube-flannel.yml
        owner: vagrant
        group: vagrant
        mode: '0644'

  roles:
    #- cg5labs.zfs
    - cg5labs.firewalld
    - geerlingguy.ntp
    - geerlingguy.containerd
    - geerlingguy.kubernetes

- name: Apply k8s nodes
  serial: 1
  hosts: k8s_nodes
  become: true
  vars:
    ansible_user: vagrant
    kubernetes_version: "1.32"
    containerd_config_cgroup_driver_systemd: true
  pre_tasks:
    - name: Disable swap immediately
      command: swapoff -a
      when: ansible_swaptotal_mb | int > 0
    - name: Remove any swap entries from /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '^\s*(.+\s+)swap(\s+.+)$'
        replace: '# \1swap\2'

#    - name: Permit traffic in default zone on port 8285/ucp for Flannel VXLAN
#      ansible.posix.firewalld:
#        port: 8285/udp
#        permanent: true
#        state: enabled
#      when: kubernetes_role in ['control_plane', 'node']
#
#    - name: Permit traffic in default zone on port 8472/ucp for Flannel VXLAN
#      ansible.posix.firewalld:
#        port: 8472/udp
#        permanent: true
#        state: enabled
#      when: kubernetes_role in ['control_plane', 'node']
#
#    - name: Enable masquerade in public zone
#      ansible.posix.firewalld:
#        masquerade: true
#        permanent: true
#        state: enabled
#
#    - name: Permit traffic in default zone for kube-worker service
#      ansible.posix.firewalld:
#        service: kube-worker
#        permanent: true
#        state: enabled
#
#    - name: Permit traffic in default zone for etcd-client service
#      ansible.posix.firewalld:
#        service: etcd-client
#        permanent: true
#        state: enabled
#
#    - name: Allow traffic from 10.244.0.0/16 (Flannel) in public zone
#      ansible.posix.firewalld:
#        source: 10.244.0.0/16
#        zone: public
#        state: enabled
#
#    # reload firewalld to apply changes
#    - name: Always reload firewalld
#      service:
#        name: firewalld
#        state: reloaded

  roles:
    #- cg5labs.zfs
    - cg5labs.firewalld
    - geerlingguy.ntp
    - geerlingguy.containerd
    - geerlingguy.kubernetes
