---
- name: Apply k8s control plane
  hosts: k8s_cp
  become: true # This applies to all tasks in this play
  serial: 1
  vars:
    kubernetes_version: "1.32"
    cni: "flannel"
    kubernetes_flannel_manifest_file: "/home/vagrant/kube-flannel.yml"
    ansible_user: vagrant
    containerd_config_cgroup_driver_systemd: true

  pre_tasks:
    - name: Disable swap immediately
      command: swapoff -a
      when: ansible_swaptotal_mb | int > 0
    - name: Remove any swap entries from /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '^\s*(.+\s+)swap(\s+.+)$'
        replace: '# \1swap\2'
      become: true

    - name: Copy kube-flannel.yml to /home/vagrant/
      ansible.builtin.copy:
        src: files/kube-flannel.yml
        dest: /home/vagrant/kube-flannel.yml
        owner: vagrant
        group: vagrant
        mode: '0644'

  roles:
    #- cg5labs.zfs
    - cg5labs.firewalld
    - geerlingguy.ntp
    - geerlingguy.containerd
    - geerlingguy.kubernetes

- name: Apply k8s nodes
  serial: 1
  hosts: k8s_nodes
  become: true
  vars:
    ansible_user: vagrant
    kubernetes_version: "1.32"
    containerd_config_cgroup_driver_systemd: true
  pre_tasks:
    - name: Disable swap immediately
      command: swapoff -a
      when: ansible_swaptotal_mb | int > 0
    - name: Remove any swap entries from /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '^\s*(.+\s+)swap(\s+.+)$'
        replace: '# \1swap\2'

  roles:
    #- cg5labs.zfs
    - cg5labs.firewalld
    - geerlingguy.ntp
    - geerlingguy.containerd
    - geerlingguy.kubernetes
