---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfspv
provisioner: zfs.csi.openebs.io
parameters:
  poolname: "zfspv-pool"
  # optional tuning
  fstype: "zfs"
  thinprovision: "yes"
  compression: "on"
  dedup: "on"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer